version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing source NPM dependencies"
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo "Building the project"
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: 'build'