export const ACCOUNT = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  BANNED: 'BANNED',
}

export const WALLETTOKEN = {
  CREATED: 'CREATED',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
}

export const MENURESPONSE = {
  CONTINUE: 'CON',
  END: 'END',
}

export const WALLETRESPONSE = {
  BALLANCE_IS: 'Your wallet balance is',
}

export const USSDMENUOPTIONS = {
  TRANSFER_FUNDS: '1',
  CHECK_BALANCE: '2', //DONE
  GENERATE_WALLET_TOKEN: '3', //DONE
  GENERATE_VOUCHER: '4',
  REDEEM_VOUCHER: '5',
  REGISTER: '6', //DONE
  UNBLOCK_ACCOUNT: '7', //DONE
}
